import { 
  getPauseMode,
  shouldIgnoreTarget,
  buildSelectors,
  buildCommonActionData,
  sendAction
} from './baseAction.js';
import { previewNode } from '../dom/domUtils.js';
export function shouldSkipElementForClick(element) {
  const textInputTypes = [
    'text', 'password', 'email', 'number',
    'search', 'tel', 'url',
    'date', 'datetime-local', 'month', 'time', 'week'
  ];
  try {
    if(!element) return false;
    const tagName = element?.tagName?.toLowerCase?.();
    if (!tagName) return false;
    if (tagName === 'select') return true;
    if (tagName=== "input" && textInputTypes.includes(element.type)){
      return true
    }
    const isTextInput = (el) =>
      el?.tagName?.toLowerCase() === 'textarea' ||
      el?.tagName?.toLowerCase() === 'select' ||
      (el?.tagName?.toLowerCase() === 'input' && textInputTypes.includes(el.type));
    if (tagName === 'textarea') return true;

    if (tagName === 'select') return true;
    if (element.type === 'checkbox' || element.type === 'radio') return true;
    if (tagName==="label" || tagName==="button"){
      const inputInside = element.querySelector('input, textarea, select');
      if (isTextInput(inputInside)) return true;
    }
    if (tagName === "label" && element.querySelector("input, textarea, select")) return true;
    if (tagName === "button" && element.querySelector("input, textarea, select")) return true;
  } catch {}
  return false;
}
export function handleClickLikeBase(e, actionType, eventLabel = 'Click') {
  // console.log(`${eventLabel} event detected:`, previewNode(e?.target));
  if (shouldIgnoreTarget(e?.target, eventLabel)) {
    console.log(`Skipping ${eventLabel} - inside browser controls or assert modal`);
    return;
  }
  if (getPauseMode && getPauseMode()) {
    // console.log(`Skipping ${eventLabel} recording - recording is paused`);
    return;
  }
  if (e.screenX === 0 && e.screenY === 0 && e.detail === 0) {
    return;
  }
  if (e && e.isTrusted === false) {
    // console.log(`Skipping synthetic ${eventLabel} generated by keyboard`, previewNode(e?.target));
    return;
  }
  
  const selectors = buildSelectors(e?.target, { minScore: 100, validate: true });
  const payload = buildCommonActionData(e, selectors);
  // console.log(`${eventLabel} event - generated selectors:`, selectors);
  if (! shouldSkipElementForClick(e?.target)) {
    sendAction(actionType, payload);
  }
}

// Click thường
export function handleClickEvent(e) {
  return handleClickLikeBase(e, 'click', 'Click');
}

// Double click
export function handleDoubleClickEvent(e) {
  return handleClickLikeBase(e, 'double_click', 'Double Click');
}

// Right click (context menu)
export function handleRightClickEvent(e) {
  return handleClickLikeBase(e, 'right_click', 'Right Click');
}

// Shift + Click
export function handleShiftClickEvent(e) {
  if (!e?.shiftKey) return;
  return handleClickLikeBase(e, 'shift_click', 'Shift Click');
}
